rss_functions-added
Nabilbmk9/yt-dropbox pull request #3
Opened 2022-08-30 11:25 UTC by Nabilbmk9

J'ai fait une modif sur get_new_podcasts()  pour récupérer seulement le tire, sans la date et sans l'extension .mp3.

J'ai ajouter les fonctions get_description_from_rss et get_tags_from_rss

2022-08-30 11:53 UTC, hgueguen requested changes

2022-08-30 11:53 UTC, hgueguen commented on src/dropbox_functions.py
> +        new_podcasts.append({'title': podcast_name[13:-4], 'path': podcast_path})
Un peu trop rigide comme méthode. Utilise plutôt split("-") pour ne récupérer que la seconde partie puis split(".") pour ne récupérer que l'avant dernière partie

2022-08-30 11:53 UTC, hgueguen commented on src/main.py
> +    podcast['tags'] = get_tags_from_rss(podcast['title'])
Super

2022-08-30 11:53 UTC, hgueguen commented on src/main.py
> +print(f"{len(new_podcasts)} new podcasts found...")
Bien vu

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
>  news_feed = feedparser.parse('https://feed.ausha.co/B6Ad3sAApEzX')
Peux-tu récupérer l'adresse du flux rss depuis une variable d'environnement ? C'est quelque chose qu'un utilisateur devra paramétrer s'il utilise ton script.

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
>                  description = description.replace("</p>", "")
Je te conseille d'extraire ce code dans une fonction remove_html_tags(description), ce sera plus lisible parce que ce morceau de code fait tâche ici

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
>                  description = description.replace("</p>", "")
tu n'auras plus qu'à écrire `description = remove_html_tags(description)`

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
> +    for meditation_podcast in news_feed.entries:
Attention au nommage de tes variables de boucle, mieux vaut écrire `for entry in news_feed.entries`

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
> +    for meditation_podcast in news_feed.entries:
Pareil ici

2022-08-30 11:53 UTC, hgueguen commented on src/rss.py
> +    for meditation_podcast in news_feed.entries:
Le fait de parcourir news_feed.entries une deuxième fois est dommage. Je pense que tu peux regrouper les deux fonctions en une `get_tags_and_description_from_rss(podcast_title)` pour être plus DRY

2022-08-31 14:08 UTC, hgueguen requested changes

2022-08-31 14:08 UTC, hgueguen commented on src/helpers.py
> +    return re.sub(clean, '', text)
C'est légal les imports dans des fonctions ?

2022-08-31 14:08 UTC, hgueguen commented on src/rss.py
>      return tags
Est-ce que tu peux récupérer les tags et la description dans une seule fonction get_tags_and_description_from_rss() ? Ça t'évite de faire cette boucle pour parcourir le flux rss plusieurs fois.

2022-08-31 14:08 UTC, hgueguen commented on src/youtube.py
> +    for video_infos in videos:
Dans tous les cas tu ne parcours la boucle qu'une fois. Pourquoi pas simplement travailler sur videos[0] ?

2022-08-31 14:08 UTC, hgueguen commented on src/youtube.py
> +        publish_at = datetime.fromisoformat(publish_at)
Lourd de mettre ça ici. À extraire dans une fonction helpers

2022-08-31 17:32 UTC, Nabilbmk9 commented on src/helpers.py
> +    return re.sub(clean, '', text)
J'ai déjà vu ça oui. Je pense que ça se fait dans certains cas comme celui ci. D'ailleurs c'est copilot qui m'a proposé ce code

2022-08-31 17:39 UTC, Nabilbmk9 commented on src/youtube.py
> +        publish_at = datetime.fromisoformat(publish_at)
Je n'ai pas encore mis a jours cette fonction

2022-08-31 17:39 UTC, Nabilbmk9 commented on src/youtube.py
> +    for video_infos in videos:
Je n'ai pas encore mis a jours cette fonction dans cette branche

2022-08-31 18:10 UTC, hgueguen requested changes

2022-08-31 18:10 UTC, hgueguen commented on src/main.py
> +    podcast['tags'] = get_tags_and_description_from_rss(podcast['title'])[1]
En faisant ça tu appelles ta fonction 2 fois, donc tu parcours la boucle deux fois. Fais plutôt : 
```
tags_and_description = get_tags_and_description_from_rss(podcast['title'])
podcast['description'] = tags_and_descriptions[0]
podcast['tags'] = ...
```

2022-08-31 18:45 UTC, Nabilbmk9 commented on src/main.py
> +    podcast['tags'] = get_tags_and_description_from_rss(podcast['title'])[1]
Smart

2022-08-31 18:49 UTC, Nabilbmk9 commented
J'ai ajouté quelques fonctions, je te laisse checker

2022-09-01 03:58 UTC, hgueguen requested changes

2022-09-01 03:58 UTC, hgueguen commented on src/main.py
>  for podcast in new_podcasts:
extra_day devrait être au pluriel et tu peux économiser des lignes en incluant l'index dans ta boucle for

2022-09-01 09:30 UTC, Nabilbmk9 commented on src/main.py
>  for podcast in new_podcasts:
Parfois j'aime bien laisser en plusieurs ligne car je trouve ça plus facile à lire

2022-09-03 04:01 UTC, hgueguen approved these changes

2022-09-03 04:02 UTC, hgueguen commented
C'est ok pour moi !

2022-09-03 11:16 UTC, merged