videos_functions added
Nabilbmk9/yt-dropbox pull request #4
Opened 2022-09-01 19:34 UTC by Nabilbmk9

J'ai avancé sur les fonctions sur les videos. Il y a pas mal de chose à changer et ajouter.

Comment je ne sais pas exactement comment faire pour push seulement les nouvelles fonctions que j'ai touché

2022-09-03 04:04 UTC, hgueguen commented
oklm @Nabilbmk9 , à toi de voir comment tu veux découper les chapitres de tes changements.

Il n'y a pas de problèmes à ce qu'il y ait beaucoup de choses à changer sur une seule branche.

2022-09-03 04:36 UTC, hgueguen requested changes

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +    return videos_list
Est-ce que tu pourrais utiliser le nom stock_videos partout ou tu as besoin d'utiliser les vidéos de stock ? Ça te permettra d'éviter la confusion entre la vidéo finale et les vidéos de stock

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +def mix_video_list(dropbox_videos_path):
appelle plutôt cette fonction `mixed_videos_list()`

ça reflètera bien le fait qu'elle ne fait pas que mixer mais qu'elle renvoie une `mixed_videos_list` & il faut mettre au pluriel vidéo puisqu'il y en a plusieurs

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
>  def ajouter_audio_sur_video(path_videoclip, path_audioclip, loop=False):
français à bannir ici

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +    string_title_to_list = podcast_title.split()
nom de variable plus clair : `words_in_title`

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +    for keyword in string_title_to_list:
`for word in words_in_title`

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +def download_video_same_length_as_audio(audio_path, dropbox_videos_path):
Est-ce que ta fonction "télécharge une vidéo de la même longueur que l'audio" ? Non.

Apparemment, ta fonction télécharge la bonne quantité de vidéos par rapport à la durée de ton audio.

Un prototypage comme `dl_enough_videos_for(audio_file)` a l'air de mieux refléter la vérité et de rendre ton code plus clair.

Tu n'as pas besoin de récupérer en paramètre dropbox_videos_path car il est dans les variables d'environnement.

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +def type_of_video_by_keyword(podcast_title):
`def find_keywords_in(podcast_title)` reflète plus simplement la vérité

2022-09-03 04:36 UTC, hgueguen commented on src/videos.py
> +def video_editing(video_folder_path, video_title):
nom de fonction vague, c'est souvent ton problème.

Pose-toi toujours la question "que fait cette fonction avec des mots simples ?", tu veux arriver à un résultat ou tu n'as qu'à lire les noms de fonction pour comprendre ce qu'elles font, sans avoir à lire l'intérieur

Ici, je verrais bien qqchose du style :
`edit_final_video`

Tu vois ce que je veux dire ?

2022-09-03 14:40 UTC, Nabilbmk9 commented on src/videos.py
> +def download_video_same_length_as_audio(audio_path, dropbox_videos_path):
la variable dropbox_videos_path est une variable défini juste avant d'utiliser la fonction. Elle varie tout le temps car le chemin des vidéos peut changer en fonction des mots contenus dans le titre.

Je peux l'enlever en ajoutant du code dans la fonction (qui est déjà un peu longue). Penses-tu vraiment que c'est plus pertinent d'enlever se paramètre?

2022-09-05 11:14 UTC, Nabilbmk9 commented on src/videos.py
> +def video_editing(video_folder_path, video_title):
Je comprends!

2022-09-06 03:30 UTC, merged